# Generated by Django 5.0.6 on 2024-06-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blogger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True, unique=True)),
                ("password", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="createuser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, null=True, unique=True)),
                ("password", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
