# Generated by Django 5.0.6 on 2024-06-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("course_description", models.TextField(max_length=200)),
            ],
        ),
    ]
