# Generated by Django 5.0.6 on 2024-06-20 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0002_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
