# Generated by Django 5.0.6 on 2024-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0003_course_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="complete",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
