# Generated by Django 5.0.6 on 2024-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0004_course_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="createuser",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
    ]
