# Generated by Django 5.0.6 on 2024-06-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0005_createuser_email"),
    ]

    operations = [
        migrations.RenameModel(old_name="Blogger", new_name="student",),
    ]
