# Generated by Django 5.0.6 on 2024-06-23 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0006_rename_blogger_student"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="password",),
        migrations.AddField(
            model_name="student",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="student",
            name="student_course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="login_registration.course",
            ),
        ),
    ]
