# Generated by Django 5.0.6 on 2024-07-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0008_alter_course_course_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("company_location", models.CharField(max_length=200, null=True)),
                ("company_website", models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="student",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
