# Generated by Django 5.0.6 on 2024-07-06 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0009_company_alter_student_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
