# Generated by Django 5.0.6 on 2024-07-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_registration", "0010_company_company_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="surname",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
